### ISSUE TITLE
Player resolution not being properly reported

### ISSUE THREAD

**Issue by vfutia** [muxinc/mux-stats-sdk-media3#66]
Our team has recently migrated to the media3 version of ExoPlayer.  As such, we have started using the `com.mux.stats.sdk.muxstats:data-media3-at_1_1:1.2.2` version of Mux.  Since switching to this version of Mux, we have observed that our player resolution is constantly reported as 1048576 x 1048576.  

We have manually tried supplying the player and screen sizes as recommended in [this](https://github.com/muxinc/mux-stats-sdk-media3) guide, but have not had any luck.

```
playerView?.let { view ->
    val width = Resources.getSystem().displayMetrics.widthPixels
    val height = Resources.getSystem().displayMetrics.heightPixels

    muxStats?.setPlayerSize(view.width, view.height)
    muxStats?.setScreenSize(width, height)
}
```

Due to the extremely large player resolution, our upscale percentage is astronomically high, resulting in us always getting a 0/100 score for video quality.

I can't determine if this is a setup issue or a library issue, but this all seemed to work find before migrating to media3.

**Comment by edwin-mejia** [comment]
_From the Zendesk Ticket:_

Hey David & team!
 
So it's my understanding that you shouldn't need to set all three of these—only a subset of them. 
 
 
If you're passing the SDK a `playerView` during initialization, the resolution tracking is automatic, and you shouldn't need to manually set the others. If you don't have a `playerView` at first, you can use `setPlayerView` to pass the SDK one later on during the session.
 
In the case where you're not using a `playerView`, you have to use `setPlayerSize`, along with `presentationChange` & `setScreenSize` for fullscreen tracking & VQ metrics. This turns off auto-tracking and requires you to manually update the resolutions as things change. Here's the [guide for manual fullscreen tracking](https://docs.mux.com/guides/monitor-androidx-media3#manually-set-when-a-video-is-being-played-full-screen).
 
 
The preferred path is to use the `playerView` way since it's automatic, but if you want to go the manual route, you can use those other methods I shared above. 
 
The dev who built this is on PTO right now, but I'll make sure to flag this to them when they return in case something is off.
 
 
 
Hope this helps!
-Edwin

**Comment by edwin-mejia** [comment]
Hey Vinnie just closing the loop here from the ZD ticket!

I spoke to our Android dev about this and they're making an internal ticket to double check the behavior around setting a `playerView` on initialization & using `setPlayerView` later on. 

This was resolved using `setPlayerView` instead of using non-null values for both.
