### ISSUE TITLE
viewdropped Events

### ISSUE THREAD

**Issue by vfutia** [muxinc/mux-stats-sdk-media3#85]
Can I get some clarification on what a "viewdropped" event is?  I was unable to find it in any of your documentation.

**Comment by daytime-em** [comment]
Hi

`viewdropped` signifies that a View ended because of inactivity, instead of the video ending explicitly. This can happen for a number of reasons. Your player may hanging without returning to IDLE or ENDED due to bugs, users could have left network coverage, or they could simply have left the player screen open after they were done watching (especially android tv users)

Hope that info helps! If you need additional assistance, you can contact support@mux.com

**Comment by daytime-em** [comment]
Please feel free to reopen if you need anything else!
